/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData female = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_cluster = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_flights = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supersonic_arrow = IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_arrows = IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
